### ISSUE TITLE
Inclusion of sklearn interface around scipy.optimize.least_squares for non-linear parametric modeling

### ISSUE THREAD

**Issue by shubhankar90** [scikit-learn-contrib/scikit-learn-contrib#10]
Request for project inclusion in scikit-learn-contrib
- Project name: ParametricModeling
- Project description: ParametricModeling is a Python class for non-linear as well as linear parametric model estimation implemented as an sklearn interface around scipy.optimize.least_squares.
- Authors: Shubhankar Mitra (shubhankar90@gmail.com)
- Current repository: https://github.com/shubhankar90/ParametricModeling
- Requirements:
  - [ ] scikit-learn compatible (check_estimator passed) scipy.optimize.least_squares is failing to find a solution for the seventh dataset being tested by check_estimator for a linear parametric model (default is linear parametric model, if the user does not supply any).
  - [x] Documentation (guide, API reference, example gallery) Added usage documentation on the github page.
  - [ ] Unit tests (coverage: xx%). Added a set of tests in ParametricModeling/tests
  - [x] Python3 compatible
  - [x] PEP8 compliant
  - [x] Continuous integration

For reference: https://github.com/scikit-learn/scikit-learn/issues/6977

**Comment by glemaitre** [comment]
@shubhankar90 Do you plan to comply with all the requirements?

**Comment by shubhankar90** [comment]
@glemaitre I can work on fulfilling all the requirements if it will be a candidate for inclusion into scikit-learn-contrib.

**Comment by glemaitre** [comment]
From what I am reading in https://github.com/scikit-learn/scikit-learn/issues/6977, it seems that it was considered as a candidate. But to be then included and reviewed, you need first to fulfill all the above points.

**Comment by shubhankar90** [comment]
Sure, I will start working on fulfilling the requirements then.

**Comment by chkoar** [comment]
@shubhankar90 what is the status on this?

**Comment by chkoar** [comment]
The requested project seems abandoned. 
So, I assume that this issue can be closed. 
Its last commit is on [Sep 29, 2017](https://github.com/shubhankar90/ParametricModeling/commits/master).

_I don't have permission to close it._

**Comment by glemaitre** [comment]
Closing. Thanks @chkoar for the follow-up.
