### ISSUE TITLE
Zenodo integration

### ISSUE THREAD

**Issue by arokem** [scikit-learn-contrib/scikit-learn-contrib#12]
Can one of the organization admins please enable Zenodo integration? 

https://guides.github.com/activities/citable-code/

This will allow us to mint DOIs for the software.

**Comment by amueller** [comment]
Done. Can you check if it works?

**Comment by arokem** [comment]
Seems to work. The organization now appears on my Zenodo dashboard, and I could flip the switch for the forest-ci project.
