### ISSUE TITLE
add boruta all relevant feature selection method?

### ISSUE THREAD

**Issue by danielhomola** [scikit-learn-contrib/scikit-learn-contrib#14]
Request for project inclusion in scikit-learn-contrib

* Project name: Boruta
* Project description: Python implementation of the Boruta feature selection method
* Authors: Daniel Homola
* Current repository: https://github.com/danielhomola/boruta_py
* Requirements:
 * [x ] scikit-learn compatible (check_estimator passed)
 * [x ] Documentation (guide, API reference, example gallery)
 * [x ] Unit tests (coverage: xx%)
 * [x ] Python3 compatible
 * [x ] PEP8 compliant
 * [x ] Continuous integration

**Comment by amueller** [comment]
Hey.
Thank you for the contribution. I think this is great.
Unfortunately I don't have time to review this right now.
Maybe someone else steps in.
I just wanted to let you know that we haven't forgotten about you ;)

**Comment by danielhomola** [comment]
Thanks a lot @amueller  :) Let's wait for the others then!

**Comment by chkoar** [comment]
@danielhomola could you make the example in `BorutaPy`'s docstring as a doctest? Also, I think that you  should not modify the `random_state` in the object initialization. It is a `scikit-learn`'s convention to not modify/validate parameters in the `__init__` method. So, you should get the `random_state` object in `_fit` using the parameter that has passed to the constructor.

Check out this link http://scikit-learn.org/stable/developers/contributing.html#parameters-and-init

**Comment by danielhomola** [comment]
Thanks for your comments @chkoar.  

Sure, I'll try and do these over the weekend. Do you think you can accept the package once these are fixed?

**Comment by danielhomola** [comment]
@chkoar Hi, I've updated the random_state to align with the scikit conventions.

I also added example files, which ensure that the test code can be ran by the user with the expected results. However doctest has no way of testing multiline output, which is what Boruta produces (quite a lot of line actually), see this thread: http://stackoverflow.com/questions/28805567/line-continuation-wrapping-in-doctest

So could you please accept the code as it is? Anyone can easily copy the test code and execute it with example data, plus the same code is also there as unit_test.

Thanks
d

**Comment by mblondel** [comment]
@danielhomola You should have received an invitation to join the organization. You should now be able to transfer your project. Once this is done, my advice is to fork the project, so that the old project url is still valid. Could you also add your project to https://github.com/scikit-learn-contrib/scikit-learn-contrib? Thanks!

**Comment by danielhomola** [comment]
Thanks a lot @mblondel. The way I understand it, I should clone the template (https://github.com/scikit-learn-contrib/project-template), follow the steps, setup docs, travis, etc and then submit a pull-request? This will take a bit of time, so bare with me :) Thanks again! d

**Comment by mblondel** [comment]
No, you just need to transfer your current project.

**Comment by danielhomola** [comment]
Really? that's great! I'll do it today or tomorrow! If you don't mind me asking, how come you don't require me to deal with all the other stuff (docs, travis, etc)? Is it because of the tiny size of my project? 

cheers

**Comment by mblondel** [comment]
The idea is to not loose your stars/forks. You can do the modifications you mention after transferring your project.

**Comment by mblondel** [comment]
Could you also add your project to the list here:
https://github.com/scikit-learn-contrib/scikit-learn-contrib
