### ISSUE TITLE
Factorial analysis library inclusion

### ISSUE THREAD

**Issue by MaxHalford** [scikit-learn-contrib/scikit-learn-contrib#15]
Request for project inclusion in scikit-learn-contrib

* Project name: Prince
* Project description: Tool for performing factorial analysis (PCA, CA, MCA, FAMD and maybe others)
* Authors: [Max Halford](https://github.com/MaxHalford)
* Current repository: [https://github.com/MaxHalford/Prince](https://github.com/MaxHalford/Prince)
* Requirements:
 * [ ] scikit-learn compatible (check_estimator passed)
 * [x] Documentation (guide, API reference, example gallery)
 * [x] Unit tests (coverage: 53%, it's low because I haven't made tests for the plotting)
 * [x] Python3 compatible
 * [x] PEP8 compliant
 * [x] Continuous integration

Hello,

I would like to ask what you think about including my library to scikit-learn-contrib. It's not ground breaking in any sense but the fact is that there isn't nice and clear library in Python for doing Correspondance Analysis and Multiple Correspondance Analysis, let alone Factor Analysis of Mixed Data.

For the while I am using fbpca for calculating the SVD, but I could easily start using scikit's TruncatedSVD. The same goes the fit/transform API, it wouldn't be too hard to do.

Best regards.

**Comment by jnothman** [comment]
sorry for the slow reply. did you close in response to the silence? why are
you proposing it here if you've not ticked that it has a
scikit-learn-compatible interface?

**Comment by MaxHalford** [comment]
I just wanted to know if it was worth making it compatible with scikit-learn beforehand, it's a bit of chicken and the egg dilemna
