### ISSUE TITLE
sklearn-pandas project inclusion request

### ISSUE THREAD

**Issue by dukebody** [scikit-learn-contrib/scikit-learn-contrib#19]
Request for project inclusion in scikit-learn-contrib after discussion at https://github.com/pandas-dev/sklearn-pandas/issues/114.

* Project name: sklearn-pandas
* Project description: Bridge between Scikit-Learn's machine learning methods and pandas-style Data Frames.
* Authors: Arnau Gil Amat, Ben Hamner, Cal Paterson, Gustavo Sena Mafra, Israel Saeta Pérez, Jeremy Howard, Jimmy Wan, Olivier Grisel, Paul Butler, Ritesh Agrawal, Vitaley Zaretskey, Zac Stewart
* Current repository: https://github.com/pandas-dev/sklearn-pandas
* Requirements:
 * [NOT APPLICABLE] scikit-learn compatible (check_estimator passed)
 * [x] Documentation (guide, API reference, example gallery)
 * [x] Unit tests (coverage: xx%)
 * [x] Python3 compatible
 * [x] PEP8 compliant
 * [x] Continuous integration

**Comment by agramfort** [comment]
where is the doc?

you could just make sure it does not break if input is a plain numpy array so check_estimator can do its job

**Comment by wdm0006** [comment]
Seems to me like this is, sort of by its own definition, scikit-learn compatible, regardless of check_estimator's appropriateness.  I think it makes sense for inclusion, this has been a populate add-on to the scikit-learn stack for a while now. Though also am having trouble locating the API reference.

**Comment by mblondel** [comment]
Seems like you already have a home in the pandas-dev organization. What would be the main benefit of moving here instead?

**Comment by dukebody** [comment]
@mblondel I personally don't really mind, I just opened this ticket upon request from https://github.com/pandas-dev/sklearn-pandas/issues/114#issue-244856731. 

Probably pandas folks prefer to keep the `pandas-dev` organization for _core_ pandas stuff and use other organizations such as `scikit-learn-contrib` or `pandas-contrib` for addons and related projects.

@wdm0006 the API reference is at the README itself: https://github.com/pandas-dev/sklearn-pandas/blob/master/README.rst

**Comment by dukebody** [comment]
@agramfort sklearn-pandas `DataFrameMapper` always expects a pandas dataframe as input, by definition. Even though it inherits from `BaseEstimator` I don't know if it can be considered a normal estimator that must pass `check_estimator`. What do you think?

**Comment by mblondel** [comment]
@dukebody I see, thanks for the clarification. 

+1 from me for inclusion

**Comment by ogrisel** [comment]
+1 for inclusion: it's good to have an "semi-official" way to write sklearn pipeline transformers where the pandas dependency is allowed.

**Comment by dukebody** [comment]
Nice. How should we proceed?

**Comment by mblondel** [comment]
@dukebody I sent you an invitation. You should be able to transfer your project to the organization (stars, watchers, etc will not be lost)

**Comment by dukebody** [comment]
@mblondel done! Thanks a lot. :)

**Comment by mblondel** [comment]
Can you add the project to the list here https://github.com/scikit-learn-contrib/scikit-learn-contrib ?

Thanks!

**Comment by dukebody** [comment]
@mblondel Done, can you check https://github.com/scikit-learn-contrib/scikit-learn-contrib/pull/24 ? :)
