### ISSUE TITLE
Request for inclusion: Averaged Cluster Augmenter

### ISSUE THREAD

**Issue by Dibillilia** [scikit-learn-contrib/scikit-learn-contrib#21]
Request for project inclusion in scikit-learn-contrib

* Project name:
AveragedClusterAugmenter

* Project description:
This is an implementation of an algorithm for preprocessing data to increase the accuracy of some estimators
by up to 40%. 

* Authors: 
Anthony Dellinger

* Current repository: 
https://github.com/Dibillilia/AveragedClusterAugmenter

* Requirements:
 * [x] scikit-learn compatible (check_estimator passed)
 * [x] Documentation (guide, API reference, example gallery)
This is not as formal as it could be, it's just the readme.md file, but it documents all the functions and parameters.
 * [x] Unit tests (coverage: xx%)
100%
 * [x] Python3 compatible
 * [x] PEP8 compliant
 * [ ] Continuous integration
I didn't implement this since the algorithm is only 100 LOC and continuous integration seemed unnecessary, but I can if its an absolute requirement.

**Comment by jnothman** [comment]
Thanks. A couple of issues:
* I think the primary contribution here is very similar to imbalanced-learn's [`ClusterCentroids` undersampling](http://contrib.scikit-learn.org/imbalanced-learn/stable/under_sampling.html). While this is good work, I'd suggest collaborating on that more mature and general project might be a good idea.
* We do not currently allow fit_transform (nor transform) to change the number of samples. imblearn uses a different method for this purpose.
* Your transformer calls `fit_transform` within transform. This seems incorrect to me. I think transform should return its input unchanged.
