### ISSUE TITLE
Request for inclusion: SkopeRules

### ISSUE THREAD

**Issue by ngoix** [scikit-learn-contrib/scikit-learn-contrib#23]
Request for project inclusion in scikit-learn-contrib

* Project name: skope-rules
* Project description: Learn rules with specified minimum precision/ minimum recall for supervised binary classification. While quite simple, we believe it can be particularly useful to the industry when experts require the model to be entirely interpretable. The output is composed of a set of decision rules.
* Authors: Florian Gardin, Ronan Gautier, Nicolas Goix, Bibi Ndiaye, Jean-Matthieu Schertzer.
* Current repository: https://github.com/skope-rules/skope-rules
* Requirements:
 * [x] scikit-learn compatible (check_estimator passed)
 * [x] Documentation (guide, API reference, example gallery)
 * [x] Unit tests (coverage: 100%)
 * [x] Python3 compatible
 * [x] PEP8 compliant
 * [x] Continuous integration

**Comment by vene** [comment]
This looks super interesting, thank you! Is the rendered doc available online anywhere, and is there some paper/tech report reference available? (The doc makes it clear what it does, but not how, as far as I can tell).

In any case I don't think this should block inclusion in sklearn-contrib.

**Comment by ngoix** [comment]
Thanks! The doc is not online yet (we can only see it through circle ci), but we plan to push the package on Pypi soon. It remains a bit of work to do, but we wanted to have a first feedback before :). Regarding the refs, we did not use any paper as the method simply consists in building lots of trees through the `BaseBagging` class, extracting the rules, and selecting them by testing them OOB (also removing too similar rules).

**Comment by jnothman** [comment]
The idea of weighted rules extracted from forests (particularly with the
goal of interpretability) has been around for a while. I saw Jerome
Friedman present it a few years back, as in
http://statweb.stanford.edu/~jhf/ftp/RuleFit.pdf, though there rules are
weighted by a linear model. I am curious about your simplified weighting
scheme, here, @ngoix.

I think it would be interesting, @ngoix, if you try to document the
relationship between this technique and the literature on rule ensemble
classifiers.

**Comment by ngoix** [comment]
Thanks for your feedback @jnothman, we added a "Links with existing litterature" in the readme, please let me know your thoughts.
Also, maybe @agramfort would like to take a look ;)

**Comment by jnothman** [comment]
Very nice comparison to literature.

**Comment by ngoix** [comment]
We just pushed the code on Pypi and added a link to the doc. @vene @jnothman

**Comment by jnothman** [comment]
Sorry I don't feel like I can devote much energy to scikit-learn-contrib. I
think what we need to do is corral the existing scikit-learn-contrib
package maintainers to maintain the overall collection.

**Comment by jnothman** [comment]
Okay, I'm inclined to just accept this. Admittedly with some bias towards the contributor who has helped us out at sklearn.

If you could do review other contrib issues, it would be great!

**Comment by jnothman** [comment]
I've created a team for you, and added @ngoix as a member. I think this is sufficient for you to transfer your repo in, and to add other contributors to the team. (I've not done this part before.) Tell me how it goes!

**Comment by ngoix** [comment]
thanks for this @jnothman ! However, it seems that I can't add team members nor repo as I'm not a maintainer of the team https://help.github.com/articles/organizing-members-into-teams/

**Comment by agramfort** [comment]
@ngoix

you should now have the rights to transfer the repo.

**Comment by ngoix** [comment]
thanks @agramfort !

**Comment by mblondel** [comment]
@ngoix Could you add the project to the list below? Thanks!

https://github.com/scikit-learn-contrib/scikit-learn-contrib/blob/master/README.md
