### ISSUE TITLE
Project documentations

### ISSUE THREAD

**Issue by mblondel** [scikit-learn-contrib/scikit-learn-contrib#3]
For lightning, @fabianp and I pushed the documentation to the `scikit-learn-contrib.github.io` project while for project-template @vighneshbirodkar pushed the documentation to the `gh-pages` branch of the project. It's not completely clear yet to me what are the benefits of one approach or the other but we should definitely be consistent, especially if more projects join the organization. Any opinions?

Maybe @amueller has an opinion as well.

**Comment by vighneshbirodkar** [comment]
From the URL point of view there is no change, i.e.
http://contrib.scikit-learn.org/project-template/
http://contrib.scikit-learn.org/lightning/

But having each project push its documentation to a separate repo keeps things more isolated, file organization and permission-wise. I would not want a gh-pages branch with a lot of projects. We don't yet know how many there will be.

**Comment by amueller** [comment]
I agree. I don't think people that have contrib projects should have push rights to the scikit-learn-contrib website. Also, I don't want to get notifications for a project updating its website ;)

**Comment by jnothman** [comment]
Does github pages support submodules?

**Comment by jnothman** [comment]
The answer is yes, and I think this may help:
https://help.github.com/articles/using-submodules-with-pages/

Does this do what we need automatically, or do we also need to periodically
pull in the submodule changes?

**Comment by mblondel** [comment]
> But having each project push its documentation to a separate repo keeps things more isolated, file organization and permission-wise

Good arguments. +1 for gh-pages!
