### ISSUE TITLE
Request for inclusion: XGP

### ISSUE THREAD

**Issue by MaxHalford** [scikit-learn-contrib/scikit-learn-contrib#31]
Request for project inclusion in scikit-learn-contrib

* Project name: XGP
* Project description: Symbolic regression (and classification)
* Authors: [Max Halford](https://github.com/MaxHalford)
* Current repository: [https://github.com/MaxHalford/xgp-python](https://github.com/MaxHalford/xgp-python)
* Requirements:
 * [X] scikit-learn compatible (check_estimator passed)
 * [X] Documentation (guide, API reference, example gallery)
 * [X] Unit tests (coverage: 89%)
 * [X] Python3 compatible
 * [X] PEP8 compliant
 * [X] Continuous integration

A bit about the library:

XGP is a symbolic regression library written in Go. The idea is to compile to a DLL and import with Python (and maybe R in the future). I've been working on it on and off for about a year and I feel it's ready to be open to the community. There's a lot to do and experiment with (particularly how symbolic regression interplays with ensembling), hopefully it will spark some people's interest.

Remarks:

- I'm facing the same issue as [here](https://github.com/scikit-learn/scikit-learn/issues/6981) because my classification model (XGPClassifier) only supports binary classification. In the future I can include multi-class classification but it's a consequent endeavour that I don't want to tackle right now.
- I haven't managed to set up Appveyor, mostly because I'm facing x32 vs x64 architecture issues when compiling the Go DLL. I'm working on it though.
- XGP isn't only for Python so I've written a [global documentation website](https://maxhalford.github.io/xgp/). I hope this is okay with you. Of course this doesn't exempt me from writing docstrings.
- Although it's high, the test coverage doesn't mean much because this is only a wrapper on top of the Go code. At the moment XGP only has a 33% test coverage, but I'm working on it. The genetic algorithm part, though, has a 100% test coverage and I've tested it for a ton of stuff.

Happy to answer any questions you may have! And of course don't hesitate if you think I've done some things wrong.

**Comment by amueller** [comment]
Thanks for the request.
This sounds cool, but I think we're a bit behind on contrib reviews / the process is not ideal yet. Lack of reply doesn't mean lack of interest.

**Comment by MaxHalford** [comment]
No worries! I'm a researcher too now 👍

**Comment by MaxHalford** [comment]
Hey, I'm working on other more worthy things at the moment and you have a lot on your plate, so I'll close this issue. I'll reopen it some other time.

**Comment by amueller** [comment]
Sorry for the lack of reply :(

**Comment by MaxHalford** [comment]
@amueller it's no problem at all! To be honest with hindsight it needs some more polishing anyway. Anyway, I'm working on an exciting new project called [creme](https://creme-ml.github.io/), I'm going to present it at PyData Amsterdam this weekend.
