### ISSUE TITLE
Request for inclusion: Stability selection

### ISSUE THREAD

**Issue by thuijskens** [scikit-learn-contrib/scikit-learn-contrib#33]
Request for project inclusion in scikit-learn-contrib

* Project name: stability_selection
* Project description: Stability selection implementation with scikit-learn compatible API.
* Authors: Thomas Huijskens
* Current repository: https://github.com/thuijskens/stability-selection
* Requirements:
 * [x] scikit-learn compatible (check_estimator passed)
 * [x] Documentation is [here](https://thuijskens.github.io/stability-selection/docs/), and a gallery with basic examples is [here](https://thuijskens.github.io/stability-selection/docs/auto_examples/index.html)
 * [x] Unit tests (coverage: 97%, the badge is a bit outdated)
 * [x] Python3 compatible
 * [x] PEP8 compliant
 * [x] Continuous integration

## Notes

I used stability selection as a feature selection algorithm successfully in some of my projects, and have been working on and off on an open-source implementation. [The algorithm](https://stat.ethz.ch/~nicolai/stability.pdf) has been around for a while (2009), and used to be in core scikit-learn until [v0.18](http://scikit-learn.org/0.18/modules/generated/sklearn.linear_model.RandomizedLasso.html#sklearn.linear_model.RandomizedLasso). The rough idea behind stability selection is to inject more noise into the original problem by generating bootstrap samples of the data, and to use a base feature selection algorithm (like the LASSO) to find out which features are important in every sampled version of the data.

My implementation is different from the original scikit-learn implementation in the following ways:
- The implementation is agnostic of the base learner, as long as it has a `coef_` or `feature_importances_` attribute. (Anything that `SelectFromModel` can use is fine)
- Because the algorithm is learner-agnostic, it does not use the efficient computation of the LASSO path in case the LASSO is the base learner. It is on my roadmap to implement this, but I'd like to get some more feedback first before spending time on this. 

## Algorithm details

For a feature to be considered stable (or important), it has to be selected in a high number of perturbed versions of the original problem. This tends to filter out features that are only weakly related to the target variable, because the additional noise introduced by the bootstrapping breaks that weak relationship. 

For more information I highly recommend reading the original paper. I have also written a short summary about the algorithm [here](https://thuijskens.github.io/2018/07/25/stability-selection/)

Thanks for taking the time to review my repository!

**Comment by agramfort** [comment]
+1 for me

can you give me admin rights to your repo so I can transfer it
to scikit-learn-contrib org?

**Comment by thuijskens** [comment]
Hi @agramfort! I've sent an invite for collaboration, I'm assuming I can give you admin rights when you confirm that.

If instead I need to transfer the repo to scikit-learn-contrib and to your username, let me know and I'll do that instead :+1:

**Comment by agramfort** [comment]
repo is transferred https://github.com/scikit-learn-contrib/stability-selection

@thuijskens can you send a PR to update https://github.com/scikit-learn-contrib/scikit-learn-contrib/blob/master/README.md ? thanks
