### ISSUE TITLE
Bootstrapping for sklearn-contrib

### ISSUE THREAD

**Issue by dsaxton** [scikit-learn-contrib/scikit-learn-contrib#35]
I've authored a package called `resample` which I believe would make a nice addition to sklearn-contrib.  The idea is to provide clean implementations of bootstrapping methods (both bootstrap samples and bootstrap confidence intervals) which can be applied to a broad class of problems, including the construction of confidence intervals for linear model coefficients, as well as prediction intervals for any other model in `sklearn`.  I think this helps to fill an inferential gap which currently exists in the `sklearn` library.

The one piece that still needs work is the documentation, as I have not been able to get the docstrings to display on Read the Docs, but once this is done I think all the below requirements are in a pretty good state.

* Project name: resample
* Project description: Randomization-based inference in Python
* Authors: Daniel Saxton
* Current repository: https://github.com/dsaxton/resample
* Requirements: numpy and scipy
 * [ x ] scikit-learn compatible (check_estimator passed)
 * [ x ] Documentation (guide, API reference, example gallery)
 * [ x ] Unit tests (coverage: 85%)
 * [ x ] Python3 compatible
 * [ x ] PEP8 compliant
 * [ x ] Continuous integration

**Comment by jnothman** [comment]
Sorry about our non-response. We haven't really got our review processes for scikit-learn-contrib sorted in a way that they function in a timely manner.
