### ISSUE TITLE
Request for project: mimic calibration

### ISSUE THREAD

**Issue by pinjutien** [scikit-learn-contrib/scikit-learn-contrib#39]
Request for project inclusion in scikit-learn-contrib

* Project name: Mimic calibration
* Project description:
This [MIMIC calibration](https://www.youtube.com/watch?v=Cg--SC76I1I) was mentioned by NYC ML Meetup talk given by Sam Steingold. With my understanding from this talk, I implemented this method.
It is a method to calibrate probability prediction of binary classification model. 
* Authors: Pin-Ju Tien 
* Current repository: https://github.com/pinjutien/mimic
* Requirements:
 * [x] scikit-learn compatible (check_estimator passed): 
    It is a calibration method instead of estimator. check_estimator allow x_train has shape (n, m) and m > 1. But, in the calibration, its goal is to calibrate prob prediction. Thus, x_train has shape (n, 1).
 * [x] Documentation (guide, API reference, example gallery)
 * [x] Unit tests (coverage: 81%)
 * [x] Python3 compatible
 * [x] PEP8 compliant.
 * [x] Continuous integration 

* Note:
I have a [pull request](https://github.com/scikit-learn/scikit-learn/pull/13344) to scikit-learn early this week. That repo is based from [here](https://github.com/pinjutien/scikit-learn/tree/mimic). But, they suggest me to post a request in scikit-learn-contrib. Let me know if this project is suitable here. Thanks.

**Comment by adrinjalali** [comment]
Could you please base your project on our template (https://github.com/scikit-learn-contrib/project-template)?

You can wait a week or so, since we're doing some cleanups and updates on the template project.

**Comment by pinjutien** [comment]
Sure. thanks for the feedback.

**Comment by amueller** [comment]
might be interesting to add an example comparing with isotonic regression, they seem quite related.

**Comment by pinjutien** [comment]
yes. it will be interesting to compare those two. I will update this comparison.

**Comment by pinjutien** [comment]
I updated the comparison between mimic, isotonic and platt scaling in [the README file](https://github.com/pinjutien/mimic). Base on my example, the prediction space from mimic is more continuous than isotonic method as we can expect.

**Comment by amueller** [comment]
Thanks. That makes sense. I guess the question is more how that is reflected in the calibration, right? So in terms of calibration curve, calibration score or brier score. Or how would you evaluate these?

**Comment by pinjutien** [comment]
Thanks for the feedback. I am working on the calibration curve and brier score. will update it later.

**Comment by pinjutien** [comment]
Hello, I update the calibration curve and brier score for both isotonic and mimic calibration.
In summary,
- brier score: isotonic and mimic are very close to each other.
- calibration curve: isotonic is more spiky as nbins increase in the calibration curve. It is because the step function of isotonic regression. (the more number of data, the less spiky of isotonic regression in the calibration curve.)

I also try to use unbalance data set, such as positive rate = 0.2, or different base estimator (GaussianNB, LinearSVC). The brier score  between mimic and isotonic calibration are also similar.

Let me know if there is something else I can show in this comparison. Thanks.

**Comment by amueller** [comment]
That's pretty neat I'd think :)

**Comment by pinjutien** [comment]
Hello, 
I made this mimic repository to fit in project-template, including those info in the doc folder (user_guide.rst ...etc). 
Do you think this project is good or useful to be one of projects of scikit-learn-contrib ?  
If yes. What is the next step to do ? From my understanding, the only thing I have not test is circleci part. If I miss anything else, please let me know. Thanks.

**Comment by pinjutien** [comment]
@adrinjalali @amueller I added a continuous integration in [this mimic calibration repo](https://github.com/pinjutien/mimic). When you have time, let me know if you have any further suggestions and thought on this. Thank you.

**Comment by agramfort** [comment]
ok to merge on my side

>

**Comment by adrinjalali** [comment]
@pinjutien I can transfer your repo to contrib if you make me a member of your repo/org I suppose.

**Comment by pinjutien** [comment]
@adrinjalali I added you as Collaborators in my repo. Let me know if it works.

**Comment by adrinjalali** [comment]
@pinjutien I think it needs to be an ownership access for me to be able to transfer the repo, I don't have those permissions now.

**Comment by adrinjalali** [comment]
The repo is now here: https://github.com/scikit-learn-contrib/mimic, and I've added you to a team with admin access to it. Thanks :)
