### ISSUE TITLE
Consider adding jeff1evesque/machine-learning repository

### ISSUE THREAD

**Issue by jeff1evesque** [scikit-learn-contrib/scikit-learn-contrib#4]
Request for project inclusion in scikit-learn-contrib

* Project name: Machine Learning
* Project description: Programmatic / Web interface to scikit-learn's svm classification 
* Authors: Jeff Levesque
* Current repository: https://github.com/jeff1evesque/machine-learning
* Requirements:
 * [ ] scikit-learn compatible (check_estimator passed)
 * [ ] Documentation (guide, API reference, example gallery)
 * [ ] Unit tests (coverage: xx%)
 * [ ] Python3 compatible
 * [ ] PEP8 compliant
 * [ ] Continuous integration

**Comment by mblondel** [comment]
I don't think a web interface is in the scope of scikit-learn-contrib. We want new algorithms that adhere to the fit / predict / transform interface.

**Comment by amueller** [comment]
I'm undecided. It would be nice for visibility of the project, but it's not really what we had intended.

**Comment by mblondel** [comment]
Is the project scikit-learn compatible?

**Comment by jeff1evesque** [comment]
This project [implements](https://github.com/jeff1evesque/machine-learning/tree/5696011368d313aaf743c93c2dc48997ed3ea7e0/puppet/environment/development/modules/sklearn/manifests) scikit-learn, as primary machine learning set of libraries.  It provides a web-interface, and a set of api, which allows users to send POST data to the server, as a programmatic interface.  This programmatic interface, allows the following:

- add dataset
- append dataset to a previously stored dataset
- generate an svm model
- implement a previously generated svm model

Per the [milestones](https://github.com/jeff1evesque/machine-learning/milestones), there's a lot more features that need to be added, and researched.  I think any exposure would allow greater awareness of this project, which would possibly bring other contributors to the project.  I am terribly slow at moving this project forward.

**Comment by jnothman** [comment]
I think, for now at least, I am -1. This belongs in the related projects
listing. I think we want to grow scikit-learn-contrib as a home for
packages that largely extend scikit-learn in its algorithmic capabilities
(including original implementations of things that won't be included in
scikit-learn, wrapping external packages, etc.).

Frontends for data and model management are quite a different kettle of
fish, competing on very different criteria. I don't think, in
scikit-learn-contrib's infancy, we should make its scope overly wide.

**Comment by jnothman** [comment]
Jeff, please do submit a PR to add this project to
https://github.com/scikit-learn/scikit-learn/blob/master/doc/related_projects.rst
in any case.
