### ISSUE TITLE
Request for inclusion: metric-learn

### ISSUE THREAD

**Issue by wdevazelhes** [scikit-learn-contrib/scikit-learn-contrib#40]
Request for project inclusion in scikit-learn-contrib

* Project name: metric-learn
* Project description: A scikit-learn compatible library for metric learning, including learning a metric from labels, from pairs, from quadruplets, and more to come
* Authors: CJ Carey, Yuan Tang, William de Vazelhes, Aurélien Bellet, and Nathalie Vauquier 
* Current repository: https://github.com/metric-learn/metric-learn
* Requirements:
 * [x] scikit-learn compatible (check_estimator passed): check_estimator passed for supervised learning estimators, but not for weakly supervised learning ones, since they take as input 3D arrays (or 2D arrays of "indicators", of size `(n_samples, 2)` for pairs, or `(n_samples, 4)` for quadruplets for instance), therefore they don't pass the tests on toy examples (we could elaborate on which tests don't pass if needed) 
 * [x] Documentation (guide, API reference, example gallery) http://metric-learn.github.io/metric-learn/
 * [x] Unit tests (coverage: 96%)
 * [x] Python3 compatible
 * [x] PEP8 compliant: <strike>it is not fully PEP8 compliant, this is indeed something we need to improve. </strike> It is now PEP8 compliant, except for the indentation
 * [x] Continuous integration: the continuous integration checks tests and coverage

**Comment by adrinjalali** [comment]
Nice, this looks like an easy one to include. I'd be happy to have it the contrib.

**Comment by rth** [comment]
Thanks @wdevazelhes, The documentation and package quality is very nice! A few comments,
 - it could be indeed useful to improve PEP8 compatibility. I have not seen that many flake8 errors, apart from the 2 space indentation. It's a (regrettable :))  choice some projects make, I wouldn't consider it a blocker.
 - it would be good to add Python 3.7 to CI tests.
 - for the weakly supervised models that take as input  another data structure than a 2D matrix, the same would apply to ML libraries for modeling time series, hybrid recommendations etc. As long as it's clearly documented, I don't think it should exclude them from scikit-learn-contrib.

Overall I'm +1 for inclusion as well. Let's wait a few more days in case there are other comments.

**Comment by agramfort** [comment]
+1 for me

**Comment by wdevazelhes** [comment]
Thanks for the review and comments @adrinjalali, @rth, and @agramfort, we just fixed the PEP8 errors (except the indentation), and added a check in travis so ensure future PRs are PEP8 compliant. We also added a test to check Python 3.7 compatibility.

**Comment by rth** [comment]
@wdevazelhes I have created the `metric-learn` team in this org and invited you there. You should have the permission to move metric-learn under this org, but if it's not the case please let me know. Also please let me know if other contributors should be added to that team.

**Comment by wdevazelhes** [comment]
@rth thanks a lot ! I'll try the transfer. Yes, could you add the other members from the `metric-learn` org ? Namely @perimosocordiae, @bellet, @nvauquie, and @terrytangyuan

**Comment by rth** [comment]
Sure, invites were sent for https://github.com/orgs/scikit-learn-contrib/teams/metric-learn/members

**Comment by wdevazelhes** [comment]
Thanks @rth
I did the transfer, though I don't know why we don't have edit access to the repo `scikit-learn-contrib/metric-learn` anymore
Did I do something wrong ? When transferring, github asked me which teams should have write access to the package, and I put the `metric-learn` team

**Comment by rth** [comment]
Great that it worked! It looks like default permissions are read. Changed them so that @scikit-learn-contrib/metric-learn members have admin permissions to https://github.com/scikit-learn-contrib/metric-learn. You would likely need to re-setup CI for the repo (unless they now handle it automatically).

Closing as resolved. If there are any other issues, please let me know by commenting in this issue :)

**Comment by terrytangyuan** [comment]
Thanks @rth! @wdevazelhes Seems like the documentation page is not available anymore: http://metric-learn.github.io/metric-learn/. Should we redirect it to http://contrib.scikit-learn.org/metric-learn/?

**Comment by bellet** [comment]
Yes if we could redirect it (ideally, with HTTP status 302: Moved permanently), that would be great

**Comment by bellet** [comment]
@terrytangyuan do you know how to do that?

**Comment by rth** [comment]
https://help.github.com/en/articles/redirects-on-github-pages might help. However as far as I understood that would require to create a `metric-learn/metric-learn` repo meaning that automatic redirects from https://github.com/metric-learn/metric-learn to the new location will stop to work.

If you do that, maybe worth forking the repo back to https://github.com/metric-learn/metric-learn, explcitly writing in the readme that the location of the repo moved, and adding redirects to Github pages.

**Comment by bellet** [comment]
Thanks, @rth. Not sure we should redirect then - forking the repo is likely to introduce confusion?
I think we also lost the doc url when we moved the package from all-umass to metric-learn organization last year - seems like Google picked up the new address rather quick

**Comment by terrytangyuan** [comment]
I would say we can probably leave it for now. I'd prefer to keep the auto-redirect to the new Github repo. I am sure users would be able to do a quick Google search and find out where the documentation is.

**Comment by wdevazelhes** [comment]
Also, there seems to be a possible solution here: https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7
Creating a Github Pages user `metric-learn` (and not a Github user), so that the repo `metric-learn/metric-learn` is still empty (hence redirection), but it allows to edit the Github Page with a redirection strategy

**Comment by bellet** [comment]
Good job @wdevazelhes, looks like it is working (for the root page anyway). Not a 301 redirection but better than nothing anyway.

**Comment by terrytangyuan** [comment]
Nice work @wdevazelhes!
