### ISSUE TITLE
Request for project inclusion: scikit-fairness

### ISSUE THREAD

**Issue by koaning** [scikit-learn-contrib/scikit-learn-contrib#45]
Request for project inclusion in scikit-learn-contrib

**Introduction** 

Hi all,

my name is Vincent Warmerdam and together with Matthijs Brouns (@MBrouns) we've started a project called scikit-lego a while ago. It's a set of scikit-learn compatible tools that we wanted to open source. It's taken off, we hear it is in production, it has 2K downloads a month and we use sklearn's testing framework to keep all the parts compatible.

Part of that library contained tools that might make models more fair and a while ago we decided it may be best to have these tools in a seperate package and to make it easier to folks to find we figured it would be good to see if this may become a contrib package. We figured scikit-fairness might be a nice working name in the meantime. So we started working ... preview is [here](https://github.com/koaning/scikit-fairness). 

On our side, it is our long term goal to make it as simple as possible for somebody new to scikit-learn to be able to pick up tools for fairness. The project will be heavily tutorial driven and there's been interest from DataKind UK to help create content. Odds are that we prefer simpler tooling that is easier to use over state of the art tooling that requires one to be knowledgeable in the field.

Then somebody on github made us aware of [fairlearn](https://github.com/fairlearn/fairlearn) and we felt it fair (no pun intented) to check in with them. We weren't aware of this effort and we acknowledge there may be an overlap in goals. We do not know what their plans are with regards to scikit-learn-contrib, but we have approached them [here](https://github.com/fairlearn/fairlearn/issues/406) just to check in.

I am sending this message to you to get feedback, we think we can offer something valuable here and we'd love to hear feedback. If you see issues with our tool then we'd love to learn early on while we check in with folks from fairlearn. 

That said, here's the info that's required. 

**Required Specs** 
* Project name: scikit-fairness
* Project description: The goal of this project is to attempt to consolidate fairness related metrics, transformers and models into a package that (hopefully) will become a contribution project to scikit-learn. We care about supporting tools that you can immediately use in your scikit-learn pipelines.
* Documentation: https://scikit-fairness.netlify.app/
* Authors: Matthijs Brouns & Vincent D. Warmerdam
* Current repository: https://github.com/koaning/scikit-fairness
* Requirements:
 * [x] scikit-learn compatible (check_estimator passed)
 * [x] Documentation (guide, API reference, example gallery) 
 * [x] Unit tests (coverage: 88%)
 * [x] Python3 compatible
 * [x] PEP8 compliant.
 * [x] Continuous integration

We did have some small questions concerning the project guidelines. 

1. On the `pypi` name, the guidelines [here](https://github.com/scikit-learn-contrib/scikit-learn-contrib/blob/master/workflow.md) suggest a naming convention but when I check some of the projects they do not seem to be followed. The [imbalanced-learn](https://github.com/scikit-learn-contrib/imbalanced-learn) project does not have `sklearn-contrib-imbalanced-learn` on pypi for example. 
2. Is it required that documentation live on the gh-pages branch? We prefer netlify.

**Comment by adrinjalali** [comment]
It's great to see you working on this topic as well. I've been working closely with fairlearn devs to make the tools there sklearn compatible, and they seem quite open about external collaborations. I'd be happy to have a fairness related package in sklearn-contrib, but as you mention, I'd be happier if we work on the same package and include the tools in that place.

Let's see what the feedback on https://github.com/fairlearn/fairlearn/issues/406 is and we can move forward from there.

**Comment by glemaitre** [comment]
It seems that the feedback in `failearn` is positive. @koaning we could  close this PR then?
