### ISSUE TITLE
Request for project inclusion : RelaxedLasso 

### ISSUE THREAD

**Issue by Flop-py** [scikit-learn-contrib/scikit-learn-contrib#47]
Request for project inclusion in scikit-learn-contrib

* Project name: RelaxedLasso
* Project description: Implementation of Relaxed Lasso Algorithm for Linear Regression
* Authors: Grégory VIAL & Flora ESTERMANN
* Current repository: https://github.com/continental/RelaxedLasso
* Requirements:
 * [x] scikit-learn compatible (check_estimator passed)
 * [x] Documentation (guide, API reference, example gallery)
 * [x] Unit tests (coverage: 94.66%)
 * [x] Python3 compatible
 * [x] PEP8 compliant
 * [x] Continuous integration

**Comment by adrinjalali** [comment]
I was wondering, if it's a single model, wouldn't it be better suited to be in scikit-learn-extra?

**Comment by adrinjalali** [comment]
What do you think @rth?

**Comment by GregVialConti** [comment]
Hello @adrinjalali and @rth , it would be great to get your feedback on this so we know the best way to move forward. Thanks in advance!

**Comment by agramfort** [comment]
I agree that it would be a better fit for new estimators in scikit-learn-extra

**Comment by GregVial** [comment]
Hello! We are still keen on moving forward with the inclusion of this estimator in scikit-learn-extra. Would you be able to run a review? Or are there other steps required on our side? Thanks in advance!

**Comment by chkoar** [comment]
> This repository has been archived by the owner on Nov 24, 2021. It is now read-only. 

Could an archived repository be transferred in the organization?

**Comment by GregVial** [comment]
The project has now moved to another location: https://github.com/GregVial/RelaxedLasso

**Comment by adrinjalali** [comment]
The repo hasn't really been touched in 3 years, I think we can close this issue since the repo is stale.
