### ISSUE TITLE
imbalanced-learn

### ISSUE THREAD

**Issue by glemaitre** [scikit-learn-contrib/scikit-learn-contrib#5]
Request for project inclusion in scikit-learn-contrib

* Project name: imbalanced-learn (aka imblearn)
* Project description: A python toolbox to tackle the curse of imbalanced datasets in machine learning
* Authors: G. Lemaitre, F. Nogueira, D. Oliveira, C. Aridas
* Current repository: https://github.com/fmfn/UnbalancedDataset
* Documentation: http://fmfn.github.io/UnbalancedDataset/
* Requirements:
 * [x] scikit-learn compatible (check_estimator passed) - This is the first test performed in each unit test
 * [x] [Documentation (guide, API reference, example gallery)](http://glemaitre.github.io/UnbalancedDataset/)
 * [x] [Unit tests (coverage: 99%)](https://coveralls.io/github/glemaitre/UnbalancedDataset?branch=master)
 * [x] [Python3 compatible](https://travis-ci.org/glemaitre/UnbalancedDataset)
 * [x] [PEP8 compliant](https://landscape.io/github/glemaitre/UnbalancedDataset/182)
 * [x] [Continuous integration](https://travis-ci.org/glemaitre/UnbalancedDataset)

**Comment by glemaitre** [comment]
Hi,

I still have on error to figure out before the library to be fully ready.
```
======================================================================

FAIL: Test the sklearn estimator compatibility

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/miniconda2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/home/travis/build/glemaitre/UnbalancedDataset/unbalanced_dataset/over_sampling/tests/test_smote.py", line 27, in test_smote_sk_estimator

    check_estimator(SMOTE)

  File "/home/travis/miniconda2/lib/python2.7/site-packages/sklearn/utils/estimator_checks.py", line 212, in check_estimator

    check_parameters_default_constructible(name, Estimator)

  File "/home/travis/miniconda2/lib/python2.7/site-packages/sklearn/utils/estimator_checks.py", line 1429, in check_parameters_default_constructible

    assert_equal(param_value, init_param.default)

AssertionError: None != 10

    'None != 10' = '%s != %s' % (safe_repr(None), safe_repr(10))

    'None != 10' = self._formatMessage('None != 10', 'None != 10')

>>  raise self.failureException('None != 10')
```

**Comment by mblondel** [comment]
Thanks! Please give us a couple of weeks so we can review your project.

Maybe a better project name would be `UnbalancedLearn`, although I would understand if you don't want / can't change the project name.

**Comment by glemaitre** [comment]
@mblondel That would be the right time to change the name. I will discuss that matter with the other contributors

**Comment by glemaitre** [comment]
Ok, on our side the documentation is now updated.
Good to go for any review.

**Comment by glemaitre** [comment]
@mblondel any feedback regarding this project?

**Comment by fabianp** [comment]
Looks good to me. Let's leave @mblondel a couple of days to reply, otherwise I'd say it's good to go.

**Comment by mblondel** [comment]
Sorry for the long delay. I will try to have a look into this next week. Or if someone else gives a second +1 that's fine too. CC @amueller @vene

Did you make a decision regarding the project name change?

**Comment by glemaitre** [comment]
@mblondel We took your advice. We go to named the project imbalanced-learn and the package `imblearn` to shorten writting during the import.

**Comment by amueller** [comment]
sounds great but I don't have time to review, sorry.

**Comment by mblondel** [comment]
@glemaitre I like the new name `imbalanced-learn`!

+1 for inclusion on my side as well. Your project has more followers than lightning actually :) 

You should now be able to transfer your repository to the contrib org.

**Comment by mblondel** [comment]
Also I have created a new `imbalanced-learn` team. Once you have moved the repository to the contrib, you can associate it with the team. This way you can give people access to your project.

**Comment by glemaitre** [comment]
Thanks, we will transfer asap depending of the timezone

**Comment by glemaitre** [comment]
The repository should be transferred by fmfn

**Comment by mblondel** [comment]
@fmfn should have received an invitation.

**Comment by mblondel** [comment]
@fmfn You should now be able to transfer the repo.

**Comment by glemaitre** [comment]
@mblondel I was checking Travis. It seems that somebody with admin rights will have to enable the CI tools (Travis, AppVeyor, circleCI, coveralls)

**Comment by mblondel** [comment]
@glemaitre I gave you admin rights.

**Comment by mblondel** [comment]
I added the project here:
https://github.com/scikit-learn-contrib/scikit-learn-contrib/blob/master/README.md

Feel free to add more maintainers (you should have commit rights).

Thanks you for this nice contribution to the scikit-learn ecosystem!

**Comment by glemaitre** [comment]
Ok I will update that.

Thanks for the smooth review
