### ISSUE TITLE
Request for project inclusion: MAPIE

### ISSUE THREAD

**Issue by gmartinonQM** [scikit-learn-contrib/scikit-learn-contrib#50]
Request for project inclusion in scikit-learn-contrib

* Project name: MAPIE
* Project description: Model Agnostic Prediction Interval Estimator. Cousin of `sklearn.calibration.CalibratedClassifierCV`, MAPIE works in regression settings and uses cross-validation residuals and submodels to compute uncertainties at prediction time. The implemented methods are recently introduced in [Rina Foygel Barber, Emmanuel J. Candès, Aaditya Ramdas, and Ryan J. Tibshirani. “Predictive inference with the jackknife+.” Ann. Statist., 49(1):486–507, February 2021](https://projecteuclid.org/journals/annals-of-statistics/volume-49/issue-1/Predictive-inference-with-the-jackknife/10.1214/20-AOS1965.full) (50+ citations to date).The obtained prediction intervals are backed by strong theoretical guarantees under exchangeability hypothesis. The uncertainty obtained is both epistemic and aleatoric.
* Authors: Vianney Taquet and Grégoire Martinon.
* Current repository: https://github.com/simai-ml/MAPIE
* Documentation: https://mapie.readthedocs.io/en/latest/
* Requirements:
 * [x] scikit-learn compatible (check_estimator passed)
 * [x] Documentation (guide, API reference, example gallery)
 * [x] Unit tests (coverage: 100%)
 * [x] Python3 compatible
 * [x] PEP8 compliant
 * [x] Continuous integration

To test scikit-learn compatibility, we use `sklearn.utils.estimator_checks.parametrize_with_checks`.

We mimick the `sklearn.linear_model.BayesianRidge` predict API by adding an `alpha` parameter in the `predict` method. The name `alpha` is less misleading than `return_std` in our case, and is more flexible since it can be a list of quantile levels used for computing several prediction intervals on the same data.

Any suggestion is very welcome, and we can take comments into account in about days.

Thanks in advance for your time.

**Comment by chkoar** [comment]
Thanks for the package. I am +1 for the inclusion. IMHO a more`scikit-learn`ish way to provide the prediction intervals would be to expose them via a `transform` method.

**Comment by adrinjalali** [comment]
since we already have certain methods such as `predict_proba` and `predict_log_proba`, I'd probably go with `predict_confidences` or something. But I'm also happy with including this, not sure if it should be it's own package or would make sense to be in `sklearn-extra`. Tagging @rth

**Comment by gmartinonQM** [comment]
Thank you very much for your feedbacks ! @rth , I would be very happy to hear yours !

**Comment by rth** [comment]
+1 for inclusion as well. @gmartinonQM , it's up to you,
 - either  you are OK contributing it to https://github.com/scikit-learn-contrib/scikit-learn-extra in which case we would be happy to include it there. For instance, because there are no other estimators planned. 
 - or you prefer it to remain a separate package, in which case please transfer the repo top me (@rth) and I will transfer it back to @scikit-learn-contrib org and add you there. Need to be admin to do that, and we currently don't have a better process.

**Comment by gmartinonQM** [comment]
Thank you very much @rth ! After discussion with the team, we prefer the second option. We have just sent you an invitation as admin for the package. Please let us know if you have received the invitation and if the transfer goes well.

**Comment by rth** [comment]
It's done. Transferred to https://github.com/scikit-learn-contrib/MAPIE there is also a @scikit-learn-contrib/mapie team where you should be able to add members if necessary. If something doesn't work please comment in this issue.

**Comment by gmartinonQM** [comment]
Thanks @rth ! Can you add my teammate [Vianney Taquet](https://github.com/vtaquet) to scikit-learn-contrib too ? It is one of the main contributors of the package.

**Comment by rth** [comment]
Can't you add him yourself? You should have enough permissions normally.

**Comment by rth** [comment]
Done.

**Comment by gmartinonQM** [comment]
Thanks !

I have a last question : in the settings tab of the new project url, we cannot manage github secrets anymore (see screenshot before/after transfer). We were used to use secrets in our github actions for publishing automatically to PyPi at each release.

@rth, is there a way to recover this functionality ?

**Before**

<img width="1042" alt="Capture d’écran 2021-07-01 à 22 00 22" src="https://user-images.githubusercontent.com/57913701/124183035-f5a47c00-dab7-11eb-88c5-f637aa4d0b60.png">


**After**

<img width="1226" alt="Capture d’écran 2021-07-01 à 22 00 40" src="https://user-images.githubusercontent.com/57913701/124183048-fa693000-dab7-11eb-9764-c2b9efc73c26.png">

**Comment by rth** [comment]
Can you try now? I ended up creating,
 - mapie team which has maintainership rights on the repo (including write access)
 - mapie/mapie-admin team which has admin right on the repo (and should allow you to set secrets)

With both of you currently. Please me know if is still doesn't work.

**Comment by gmartinonQM** [comment]
Perfect ! We have retrieved our secrets and our PyPi publication workflow ! Thank you very much !

**Comment by gmartinonQM** [comment]
Hi @rth, we would like to remove CircleCI builds for MAPIE (actually used for CI of the docs), since there is a large redundancy with readthedocs CI. However, we cannot manage CircleCI builds on behalf of scikit-learn-contrib organization (see screenshot).

Could you please click on "stop building" on CircleCI's MAPIE settings (Project Settings > Overview > scroll to bottom) ?

![Capture d’écran 2021-07-05 à 11 30 32](https://user-images.githubusercontent.com/57913701/124450780-0c332780-dd85-11eb-9f3f-1ad54e7b03cd.png)

**Comment by rth** [comment]
@gmartinonQM Done.
