### ISSUE TITLE
Request for inclusion for DenMune clustering algorithm

### ISSUE THREAD

**Issue by egy1st** [scikit-learn-contrib/scikit-learn-contrib#52]
Request for project inclusion in scikit-learn-contrib

* Project name: DenMune
* Project description: DenMune a clustering algorithm that can find clusters of arbitrary size, shapes and densities in two-dimensions. Higher dimensions are first reduced to 2-D using the t-sne. The algorithm relies on a single parameter K (the number of nearest neighbors). The results show the superiority of the algorithm.
* Authors: Mohamed Abbas, Adel ElZoghabi, Amin Shoukry
* Current repository: https://github.com/egy1st/denmune-clustering-algorithm
* Requirements:
 * [x] scikit-learn compatible (check_estimator passed)
 * [X] Documentation (guide, API reference, example gallery)
 * [x] Unit tests (coverage: 100%)
 * [X] Python3 compatible
 * [x] PEP8 compliant
 * [x] Continuous integration

**Comment by adrinjalali** [comment]
@smarie would you have opinions on this?

**Comment by smarie** [comment]
Hi @adrinjalali sorry for the late answer. I am not familiar with DenMune clustering algorithm. 

 - I had a quick look at the journal pre-proof. From the results, it seems like a serious competitor to some algorithms that are said to be already implemented in scikit-learn (Hdbscan, Spectral Clustering and Kmeans++). https://scikit-learn.org/stable/modules/clustering.html . 
However note (for @egy1st ): I have trouble understanding where the HDBSCAN implementation used for the paper was found, as in scikit-learn only DBSCAN and OPTICS are available. Maybe I read too fast?

 - In the paper they mention some other algorithms that may be worth including but are not yet in sklearn: NBIR, CBKM, RS, FINCH, FastDP and RCC

 - Finally they mention a large set of datasets used to create the results table. These datasets might be worth including too if not already (https://scikit-learn.org/stable/datasets.html) 

If scikit-learn is to serve as a reference place where all state-of-the art clustering algorithms can be easily found and used according to the same pattern, then I would be supportive of including DenMune. On the other hand, that would mean that we should probably also include NBIR, CBKM, RS, FINCH, FastDP and RCC (and the like) if their authors require it.

This calls for some governance policy/line that I may not be aware of as of today. What is the core team's opinion on this @thomasjpfan ? (debate for future core team sync meeting?) Total openness as long as the Machine Learning problem is one that is in scope of sklearn ? (here, clustering) Or is there some filtering ? Community voting ? Package popularity threshold ? etc.

I would personally be in favour of **at least** including a documentation chapter within the sklearn clustering section, containing an example of how to install and use DenMune.

**Comment by adrinjalali** [comment]
Thanks for the insights @smarie . This is for scikit-learn-contrib and not the scikit-learn core package. So we hvae more relaxed constraints on including libraries and algorithms here.

Our policy so far as been that it should be documented, be tested, have a CI, and be compatible with sklearn, and be relevant to the community.

**Comment by egy1st** [comment]
Hello @adrinjalali 
any update?

**Comment by adrinjalali** [comment]
Do you plan to maintain this library? It doesn't seem to have been maintained in the past 7 months or so.

**Comment by egy1st** [comment]
Hello @adrinjalali 

Sure. I should mention that  this version was released after many many revisions as it seems from the rlease history on PyPi (https://pypi.org/project/denmune/#history); thus it is mostly stable. anyway, any issue reported, I work on it immediately as it is seen from the only issue reported since it was formly released (https://github.com/egy1st/denmune-clustering-algorithm/issues/5).

I have done alot of work, proveded rich documentation & tutorials, and provided several testing cases on many workspaces. Actualy DenMune is not  an ordinary clustering algorithm, rather it can be considered a new clustering concept/technique which I firstly introduced in an algorithm called CMune in 2012, which was followed by many reasearcher since then, The most known algorithm to follow this concept was Density Peak Clustering Algorithm published in 2014.

Mohamed Ali

**Comment by adrinjalali** [comment]
Cool, this sounds good to me then. If there are no objections from others, happy to move the ownership under the contrib org this week.

**Comment by egy1st** [comment]
> Cool, this sounds good to me then. If there are no objections from others, happy to move the ownership under the contrib org this week.

I'm so happy and very excited to hear that. Thanks @adrinjalali

**Comment by adrinjalali** [comment]
@egy1st  Since there are no objections, could you please transfer the repository's ownership to me, so that I can then move it to the contrib org, and then will add you as an owner there.

**Comment by egy1st** [comment]
> > Cool, this sounds good to me then. If there are no objections from others, happy to move the ownership under the contrib org this week.
> 
> I'm so happy and very excited to hear that. Thanks @adrinjalali

@adrinjalali Transfer request sent.

**Comment by adrinjalali** [comment]
It's done, and you're an admin now: https://github.com/scikit-learn-contrib/denmune-clustering-algorithm

Please try to have all future contributions through PRs from your own fork :)

**Comment by egy1st** [comment]
Hello @adrinjalali 
would you please add this project to the projects listed in main readme page (https://github.com/scikit-learn-contrib/scikit-learn-contrib/blob/master/README.md)

Mohamed

**Comment by adrinjalali** [comment]
Please send a PR and we can approve it :)

**Comment by egy1st** [comment]
Hello @adrinjalali,

I am writing to propose the inclusion of the DenMune clustering algorithm in the scikit-learn library. DenMune is a novel, density-peak based clustering algorithm that has demonstrated superior performance in handling complex datasets with clusters of arbitrary shapes, varying densities, and unbalanced class distributions.

The key strengths of DenMune that make it a valuable addition to scikit-learn are:

1. **Novel and Effective Algorithm**: DenMune utilizes mutual nearest neighbors to identify and expand dense cluster cores, while automatically removing noise. It outperforms many state-of-the-art algorithms on benchmark datasets.

2. **Single Parameter**: DenMune requires only a single parameter (k-nearest neighbors), making it easy to use and tune. It is also stable and robust over a wide range of k values.

3. **Handles Complex Data**: DenMune can effectively handle datasets with complex cluster structures that are challenging for traditional algorithms.

4. **Scikit-learn Compatible**: The pyMune library, implementing DenMune, is fully compatible with scikit-learn and adheres to its API conventions.

5. **Open-Source and Well-Documented**: Both the algorithm and its implementation (pyMune) are open-source (BSD-licensed) and well-documented, with extensive examples and tutorials available.

6. **Reproducibility and Accessibility**: DenMune has been integrated with CodeOcean and Binder for easy reproducibility and accessibility.

7. **Validation and Impact**: The algorithm has been rigorously validated and published in reputable journals, including the Journal of Pattern Recognition and the Journal of Software Impacts. It has gained significant traction, with over 200,000 downloads and adoption in the scikit-learn-contrib repository.

8. **Active Development and Maintenance**: The DenMune project is actively maintained, with continuous integration, code coverage, and security scanning in place.

Including DenMune in scikit-learn would provide the broader machine learning community with a powerful and accessible clustering solution for complex datasets. It would also contribute to the diversity and robustness of the clustering algorithms available in scikit-learn.

I would be pleased to work closely with the scikit-learn maintainers to ensure a smooth integration process and address any potential concerns or requirements. Please let me know if you need any additional information or if you have any questions.

Thank you for your consideration.

Best regards,
Mohamed Abbas, PhD

**Comment by adrinjalali** [comment]
This certainly doesn't pass our inclusion criteria for the main library unfortunately.

**Comment by egy1st** [comment]
Kindly @adrinjalal, which criteria it does not pass

**Comment by adrinjalali** [comment]
It's too recent, and not enough citations compared to what gets included these days. So this fits better in its own package.

**Comment by egy1st** [comment]
Hello @adrinjalali,

I would like to propose DenMune for consideration toward inclusion in the core of the scikit-learn, or guidance on what is still required to reach that stage. DenMune is already maintained within the scikit-learn-contrib and has demonstrated strong maturity and impact: it has 92+ citations (mostly Scopus-indexed), ~350k downloads worldwide, and a dedicated software publication (pyMune) in an Elsevier journal. It has also been selected by Code Ocean as a reproducible research capsule and received an invitation from Elsevier Software Impacts for publication in the “R badged articles” special issue, reflecting reproducibility and research impact. Additionally, the algorithm has been used in multiple funded projects, including work supported by 20+ applied research grants.

Given this level of academic validation, reproducibility recognition, and real-world adoption, I believe DenMune may be ready for evaluation against core inclusion criteria. I am happy to contribute to any required improvements.
Thank you.
