### ISSUE TITLE
Request for project inclusion: skglm

### ISSUE THREAD

**Issue by QB3** [scikit-learn-contrib/scikit-learn-contrib#54]
Request for project inclusion in scikit-learn-contrib

* Project name: skglm
* Project description: skglm is a library that provide better sparse generalized linear model for scikit-learn. Its main features are:
  *speed*: problems with millions of features can be solved in seconds. Default solvers rely on efficient coordinate descent with numba just in time compilation.
    *flexibility*: virtually any combination of datafit and penalty can be implemented in a few lines of code.
    *sklearn API*: all estimators are drop-in replacements for scikit-learn.
    *scope*: support for many missing models in scikit-learn - weighted Lasso, arbitrary group penalties, non convex sparse penalties, etc.

* Authors: Q. Bertrand, Q. Klopfenstein, P.-A. Bannier, G. Gidel and M. Massias
* Current repository: https://github.com/mathurinm/skglm
* Requirements:
 * [x] scikit-learn compatible (check_estimator passed): https://github.com/mathurinm/skglm/blob/21fcbfeca17731d6608a414828b427a6bf3bdb76/skglm/tests/test_estimators.py#L89
 * [x] Documentation (guide, API reference, example gallery): https://mathurinm.github.io/skglm/
 * [x] Unit tests  (coverage: 66%, please note that we use numba and that all the jitted part appear as not tested, but they are)
 * [x] Python3 compatible
 * [x] PEP8 compliant: https://github.com/mathurinm/skglm/blob/d302600a1ef4c509e97451e3e1fec74acf71b56f/.github/workflows/flake8.yml#L28
 * [x] Continuous integration: https://github.com/mathurinm/skglm/blob/21fcbfeca17731d6608a414828b427a6bf3bdb76/.github/workflows/main.yml#L27

**Comment by agramfort** [comment]
I can take care of the transfer. @QB3 or @mathurinm can you give me admin access to the skglm repo so I can do the transfer?

**Comment by mathurinm** [comment]
Thank you @agramfort 
It is now in http://github.com/scikit-learn-contrib/skglm

The issue can be closed
