### ISSUE TITLE
Request for project inclusion: hiclass

### ISSUE THREAD

**Issue by mirand863** [scikit-learn-contrib/scikit-learn-contrib#58]
Request for project inclusion in scikit-learn-contrib

* Project name: hiclass
* Project description: an open-source Python library for hierarchical classification
* Authors: Fábio M. Miranda, Niklas Köehnecke and Bernhard Y. Renard
* Current repository: https://github.com/mirand863/hiclass
* Requirements:
 * [X] scikit-learn compatible (check_estimator passed)
 Using parametrize_with_checks, e.g., [https://github.com/mirand863/hiclass/blob/main/tests/test_LocalClassifierPerLevel.py#L15](https://github.com/mirand863/hiclass/blob/main/tests/test_LocalClassifierPerLevel.py#L15)
 * [X] Documentation (guide, API reference, example gallery)
 Documentation with guide, gallery and API reference available at [https://hiclass.readthedocs.io/en/latest/](https://hiclass.readthedocs.io/en/latest/)
 * [X] Unit tests (coverage: 98%)
 * [X] Python3 compatible
 * [X] PEP8 compliant
 Enforced by the uncompromising code formatter black
 * [X] Continuous integration

**Comment by mirand863** [comment]
> This looks good to me. If there are no objections from others in a week or so, please ping me back and I can handle the transfer to the contrib org.

Hi @adrinjalali,

Thank you very much for taking time to review this PR! A week has passed and no one objected so far. Shall we proceed?

**Comment by adrinjalali** [comment]
@mirand863 yes, please send a ownership transfer request to my user (`adrinjalali`), and then I can proceed by moving it to the org.

**Comment by adrinjalali** [comment]
Done, you now are an admin for this repo: https://github.com/scikit-learn-contrib/hiclass
