### ISSUE TITLE
Request for project inclusion: sk-transformers

### ISSUE THREAD

**Issue by chrislemke** [scikit-learn-contrib/scikit-learn-contrib#59]
Request for project inclusion in scikit-learn-contrib

* Project name: sk-transformers
* Project description: A collection of various scikit-learn compatible transformers for all kinds of preprocessing and feature engineering steps 
* Authors: Chris Lemke and  Prem Srinivasan
* Current repository: https://github.com/chrislemke/sk-transformers
* Requirements:
 * [] scikit-learn compatible (check_estimator passed)
 * [X] Documentation (guide, API reference, example gallery)
 * [X] Unit tests (coverage: 99%)
 * [X] Python3 compatible
 * [X] PEP8 compliant
 * [X] Continuous integration

**Comment by adrinjalali** [comment]
I can't find the tests for sklearn compatibility, you can simply use this: https://scikit-learn.org/dev/modules/generated/sklearn.utils.estimator_checks.parametrize_with_checks.html#sklearn.utils.estimator_checks.parametrize_with_checks

**Comment by chrislemke** [comment]
Probably my description is misleading. Since only transformers and no estimators are we did not test `check_estimator`.

**Comment by chrislemke** [comment]
Ahh. Alright, will care about it. Thanks for the hint :-)
