### ISSUE TITLE
New contribution: sklearn-forest-ci

### ISSUE THREAD

**Issue by arokem** [scikit-learn-contrib/scikit-learn-contrib#6]
Request for project inclusion in scikit-learn-contrib

* Project name: sklearn-forest-ci
* Project description: Confidence intervals for scikit learn forest estimators.
* Authors: @kpolimis, @bhazelton, @arokem
* Current repository: https://github.com/uwescience/sklearn-forest-ci
* Requirements:
 * [x ] scikit-learn compatible (check_estimator *irrelevant*)
 * [x ] Documentation (guide, API reference, example gallery)
 * [x ] Unit tests (coverage: 91%; note the inclusion of duecredit affects our coverage adversely; module code is 100% covered)
 * [x ] Python3 compatible
 * [x ] PEP8 compliant
 * [x ] Continuous integration

**Comment by amueller** [comment]
thanks :) ping @glouppe

**Comment by fabianp** [comment]
+1 for me

**Comment by glouppe** [comment]
This is great! However, I am wondering whether this needs to live in its own independent package? FYI, I implemented the same jacknife estimate some months ago in https://github.com/scikit-learn/scikit-learn/pull/5532 (however, that PR has now stalled).

**Comment by mblondel** [comment]
Looks like the paper referenced has 28 citations.

**Comment by mblondel** [comment]
In the example "Plotting Classification Forest Error Bars", I would add a legend to indicate what blue and green dots indicate (I guess spam / non-spam).

**Comment by arokem** [comment]
Yes - the reason we proposed this here, instead of on scikit-learn itself is that this is a relatively new method.

**Comment by arokem** [comment]
Thanks for the comment about the legend: https://github.com/uwescience/sklearn-forest-ci/pull/14

**Comment by mblondel** [comment]
+1 on my side for a contrib project. If the approach implemented becomes popular, we can move it to sklearn later. Actually, this is one of the motivations of the contrib organization.

Regarding the project name, my first thought was that `ci` stands for `continuous integration`. I would remove the `sklearn-` prefix which doesn't bring much, and replace the title with something more explicit, like `forest-confidence` or `forest-confidence-interval`.

**Comment by arokem** [comment]
Thanks the comments. I like `forest-confidence-interval`

For the package name, how about `forestci`, omiting the `skl` prefix?

**Comment by mblondel** [comment]
> For the package name, how about `forestci`, omiting the `skl` prefix?

Sounds good to me!

**Comment by arokem** [comment]
OK - what's the next step from our point of view?

IIUC, we go ahead to refactor/rename accordingly, tag and then upload our
0.1 to PyPI?

**Comment by agramfort** [comment]
Yes on my side 






On Sat, Jul 16, 2016 at 7:46 PM +0200, "Ariel Rokem" <notifications@github.com> wrote:










OK - what's the next step from our point of view?



IIUC, we go ahead to refactor/rename accordingly, tag and then upload our

0.1 to PyPI?





On Fri, Jul 15, 2016 at 9:28 PM, Mathieu Blondel <notifications@github.com>

wrote:

**Comment by mblondel** [comment]
@arokem Invitation to join contrib organization and forest-confidence-interval team sent :) You should hopefully be able to move your project to the organization.

**Comment by arokem** [comment]
Thanks! Could you please add @kpolimis and @bhazelton to this team?

I don't seem to have the permissions, but the GitHub UI might just be
eluding me...

**Comment by mblondel** [comment]
Looks like in order to move a repo from one org to another, owner privilege is necessary in both orgs.

https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/

This should be fixed on our side.

**Comment by arokem** [comment]
What's the right thing to do here?

Move it with the current name and then rename the repo/package when it's
under scikit-learn-contrib?

**Comment by mblondel** [comment]
Since you have owner privilege in both orgs, I guess renaming before or after doesn't matter?

**Comment by arokem** [comment]
Just pinging @kpolimis and @bhazelton one more time: any thoughts about renaming the repo to `forest-confidence-interval` and package to `forestci`? If I don't hear back from you within the next couple of days, I will assume that you are happy with that.

**Comment by bhazelton** [comment]
Sounds good to me.

**Comment by kpolimis** [comment]
Those names work great, Ariel.

**Comment by arokem** [comment]
OK - I've moved it, and renamed on https://github.com/scikit-learn-contrib/forest-confidence-interval/pull/17. I guess we should also move the docs to be on scikit-learn-contrib.github.io?

**Comment by mblondel** [comment]
The website is in your gh-pages branch. URL:
http://contrib.scikit-learn.org/forest-confidence-interval/

**Comment by mblondel** [comment]
I added the project here:
https://github.com/scikit-learn-contrib/scikit-learn-contrib/blob/master/README.md

Feel free to add more maintainers (you should have commit rights).

Thanks you for this nice contribution to the scikit-learn ecosystem!
