### ISSUE TITLE
Request for project inclusion in scikit-learn-contrib: Skforecast

### ISSUE THREAD

**Issue by JavierEscobarOrtiz** [scikit-learn-contrib/scikit-learn-contrib#60]
Request for project inclusion in scikit-learn-contrib

Hi! We have seen on the [Related Projects](https://scikit-learn.org/stable/related_projects.html) page that projects closely related to scikit-learn are mentioned. We would like to propose the inclusion of Skforecast in that list.

Skforecast is not focused on developing new estimators, but rather on facilitating using scikit-learn regressors as multi-step forecasters. It also works with any regressor compatible with the scikit-learn API (pipelines, CatBoost, LightGBM, XGBoost, Ranger...).

* Project name: Skforecast
* Project description: Skforecast is a python library that eases using scikit-learn regressors as multi-step forecasters. It also works with any regressor compatible with the scikit-learn API (pipelines, CatBoost, LightGBM, XGBoost, Ranger...).
* Authors: Joaquín Amat Rodrigo (https://github.com/JoaquinAmatRodrigo), Javier Escobar Ortiz (https://github.com/JavierEscobarOrtiz)
* Current repository: https://github.com/JoaquinAmatRodrigo/skforecast

Are we opening the issue in the right place?

Thank you!

**Comment by JavierEscobarOrtiz** [comment]
Hello @adrinjalali,

Thank you for your response! I am sorry because maybe there is a little misunderstanding, our intention is to appear on the [Related Projects](https://scikit-learn.org/stable/related_projects.html) page. Are we opening the issue in the rigth place?

**Comment by adrinjalali** [comment]
I see, for that you need to open an issue on the https://github.com/scikit-learn/scikit-learn/ repo itself :)

**Comment by JavierEscobarOrtiz** [comment]
Thank you @adrinjalali !
