### ISSUE TITLE
Request for Project Inclusion: scikit-matter

### ISSUE THREAD

**Issue by rosecers** [scikit-learn-contrib/scikit-learn-contrib#62]
Request for project inclusion in scikit-learn-contrib

* Project name: scikit-matter
* Project description: scikit-matter is a collection of [scikit-learn](https://scikit.org/) compatible utilities that implement methods born out of the materials science and chemistry communities.
* Authors: @agoscinski, @rosecers, @vprincipe, @luthaf, @picocentauri, @hurricane642, @bhelfrecht, @ceriottim
* Current repository: https://github.com/lab-cosmo/scikit-matter
* Requirements:
 * [X] scikit-learn compatible (check_estimator passed)
 * [X] [Documentation](scikit-matter.readthedocs.io) (guide, API reference, example gallery): 
 * [X] Unit tests (coverage: 97%)
 * [X] Python3 compatible
 * [X] PEP8 compliant
 * [X] Continuous integration

Furthermore, [scikit-matter](scikit-matter.readthedocs.io) is the focus of the article in Open-Research Europe available here: https://open-research-europe.ec.europa.eu/articles/3-81/v1

**Comment by adrinjalali** [comment]
Thanks for the request. It looks great to me, but with a quick look, I couldn't find where you check for API compatibility. Could you point me to where you do it, or if you're not, you can add the tests for your estimators as explain here: https://scikit-learn.org/stable/modules/generated/sklearn.utils.estimator_checks.parametrize_with_checks.html#sklearn.utils.estimator_checks.parametrize_with_checks

**Comment by rosecers** [comment]
@adrinjalali Thanks for the quick reply! I hadn't put an explicit set of tests in, so I've put them in today, awaiting some input from my team.

**Comment by rosecers** [comment]
Hi @adrinjalali, we've added the explicit estimator checks -- what are next steps?

**Comment by adrinjalali** [comment]
Nice, I'm glad this helped with some clean ups @rosecers 

You can transfer ownership to me, and then I'll move it to the org and add you as an owner, and you can add your other collaborators as well.

**Comment by adrinjalali** [comment]
@ceriottm thanks. But the transfer is expired (it's valid for only a day).

Could you please send a new transfer request?
