### ISSUE TITLE
Request for projet inclusion: Qolmat

### ISSUE THREAD

**Issue by JulienRoussel77** [scikit-learn-contrib/scikit-learn-contrib#63]
Request for project inclusion in scikit-learn-contrib

* Project name: Qolmat
* Project description: Model selection for missing values imputation, based on cross-validation. Comparing imputation methods requires to make assumptions concerning the missingness distribution, and to generate adequate masks during cross-validation. The package also includes Transformer classes imputing missing data with with fit_transform methods : mainly a RPCA algorithm, an EM algorithm and Deep Learning approaches. The project adresses both tabular and temporal data, and it tackles a lack in multivariate time series implementations.
* Authors: Julien Roussel, Hông-Lan Botterman, Firas Dakhli, Mikaïl Duran, Rima Hajou, Anh Khoa Ngo Ho, Guillaume Saës, Vianney Taquet
* Current repository: https://github.com/Quantmetry/qolmat
* Requirements:
 * [x] scikit-learn compatible (check_estimator passed, except for check_parameters_default_constructible and check_no_attributes_set_in_init)
 * [x] Documentation (guide, API reference, example gallery)
 * [x] Unit tests (coverage: 78%)
 * [x] Python3 compatible
 * [x] PEP8 compliant
 * [x] Continuous integration

**Comment by adrinjalali** [comment]
This is in quite a nice state, but also quite new. Happy to consider it in a couple of months, making sure it doesn't go stale soon.

**Comment by JulienRoussel77** [comment]
Hello Adrin, this is an ongoing research projet at Quantmetry. We intend to keep creating features in the next months, and at least to maintain the projet on the long run as we do for Mapie. We are about to release a new version where all check_estimator tests are passing. We wanted to first check that you agree with the scientific interest of our contribution.

**Comment by adrinjalali** [comment]
There's growing evidence that imputation is not as important as once we all thought, and that using models which handle missing values natively is a better idea. But if this project is helping some folks, no objection for its inclusion.

**Comment by JulienRoussel77** [comment]
Hello, we just released a new version of the library and we will continue to add features and tutorials/benchmark to help users figure out whether imputation is what they need in their specific case, and what they can gain from it.

**Comment by chkoar** [comment]
qolmat has all the requirements in order to be a scikit-learn-contrib project. +1 from me.

**Comment by JulienRoussel77** [comment]
Hello @adrinjalali, we have reached a development state where we checked all requirements for inclusion based on technical criteria. We would gladly take feedbacks from you and the community concerning our main features, positioning and scientific direction of Qolmat, as well as necessary improvements to make it a scikit-learn contrib library.

**Comment by adrinjalali** [comment]
if there are no objections within a week, happy to transfer the repo to the contrib org.

**Comment by JulienRoussel77** [comment]
Hello @adrinjalali, happy new year to you and to the rest of the team! Have you transferred the repo yet, or is there something I should do to help?

**Comment by JulienRoussel77** [comment]
@adrinjalali No problem, I didn't see your answer either. Transfering the ownership does not seem possible on GitHub ("You can only transfer a repository from an organization to yourself at this time"). I invited you as Admin, this is how they proceeded for our colleagues on MAPIE at the time (https://github.com/scikit-learn-contrib/scikit-learn-contrib/issues/50)

**Comment by adrinjalali** [comment]
Done.

**Comment by JulienRoussel77** [comment]
Thanks Adrin! We also have a budget this year to develop new features, this is just the beginning!
