### ISSUE TITLE
Request for project inclusion: sklearn-ann

### ISSUE THREAD

**Issue by frankier** [scikit-learn-contrib/scikit-learn-contrib#64]
Request for project inclusion in scikit-learn-contrib

* Project name: sklearn-ann
* Project description: Integration with (approximate) nearest neighbors libraries for scikit-learn + clustering based on with kNN-graphs.
* Authors: Frankie Robertson, Philipp Angerer
* Current repository: https://github.com/frankier/sklearn-ann
* Requirements:
 * [x] scikit-learn compatible (check_estimator passed) [Mostly - some transformers do not pickle at the moment -- this could be worked around in future versions and is documented)
 * [x] Documentation (guide, API reference, example gallery)
 * [x] Unit tests (coverage: xx%)
 * [x] Python3 compatible
 * [x] PEP8 compliant
 * [x] Continuous integration

**Comment by frankier** [comment]
@adrinjalali Ping

**Comment by adrinjalali** [comment]
CI seems to be failing and the last commit is from 5-6 months ago. Still working on this?

**Comment by flying-sheep** [comment]
You mean in the sense of “is this maintained” or “is this WIP”? Yes to the former, no to the latter.

That CI failure was probably a fluke. I just updated the docs and everything seems fine: https://github.com/frankier/sklearn-ann/pull/17

**Comment by flying-sheep** [comment]
OK, so there isn’t actually any problem: https://github.com/frankier/sklearn-ann/issues/18

**Comment by frankier** [comment]
@adrinjalali Thanks for the heads up and thanks @flying-sheep for fixing it! Any info on next steps for this?

**Comment by frankier** [comment]
@adrinjalali What are the next steps? Do you still have time to review these? Should we find more reviewers to speed up the process?

**Comment by adrinjalali** [comment]
Since I don't see any other objections, we can add it to the org. You can send a request to transfer the ownership of the repo to me, and I'll take care of it.

**Comment by frankier** [comment]
Okay great! Done.

**Comment by adrinjalali** [comment]
Done

**Comment by flying-sheep** [comment]
Hi, seems like I don’t have admin rights for the repo. Does @frankier or how does that work?

I’d like to release it on PyPI: https://github.com/scikit-learn-contrib/sklearn-ann/pull/20
