### ISSUE TITLE
Request for Project Inclusion: FastCan

### ISSUE THREAD

**Issue by MatthewSZhang** [scikit-learn-contrib/scikit-learn-contrib#67]
Request for project inclusion in scikit-learn-contrib

* Project name: fastcan
* Project description: A Fast Canonical-Correlation-Based Feature Selection Algorithm.
* Authors: @MatthewSZhang
* Current repository: https://github.com/MatthewSZhang/fastcan
* Requirements:
 * [x] scikit-learn compatible (check_estimator passed)
 * [x] Documentation (guide, API reference, example gallery)
 * [x] Unit tests (coverage: 100%)
 * [x] Python3 compatible
 * [x] PEP8 compliant
 * [x] Continuous integration

**Comment by adrinjalali** [comment]
This looks real nice. If there are no objections within a week, happy to include it.

**Comment by MatthewSZhang** [comment]
Hi @adrinjalali shall we move on :)

**Comment by adrinjalali** [comment]
Cool. Now you need to transfer ownership to me, and then I can move it to the org, and add you as an admin/owner.

**Comment by MatthewSZhang** [comment]
Hi @adrinjalali I have transferred ownership to you

**Comment by adrinjalali** [comment]
Done!
