### ISSUE TITLE
polylearn: higher order factorization machines and polynomial networks in Python

### ISSUE THREAD

**Issue by vene** [scikit-learn-contrib/scikit-learn-contrib#7]
Hey folks, here's my request for project inclusion in scikit-learn-contrib.

* Project name: `polylearn`
* Project description: higher order factorization machines and polynomial networks in Python (implements the solvers from @mblondel et al's [ICML 2016 paper](http://www.mblondel.org/publications/mblondel-icml2016.pdf).
* Authors: Vlad Niculae (@vene)
* Current repository: https://github.com/vene/polylearn
* Requirements:
 * [ ] scikit-learn compatible (`check_estimator` passed) (see notes)
 * [x] [Documentation (guide, API reference, example gallery)](http://vene.ro/polylearn) (see notes)
 * [x] Unit tests (coverage: 98%)
 * [x] Python3 compatible
 * [x] PEP8 compliant  (*I should really add CI for this...*)
 * [x] Continuous integration

**Notes:**

* There could certainly be more narrative docs and more examples. I will work on that. 
* The two regressor classes pass `check_estimator`, but the classifier classes do not. The only reason for this is because `polylearn` only does binary classification, raising an error on multiclass or multioutput targets. The common tests don't like this, which I think is too strict. Should we make the `scikit-learn` tests more leninent with this scenario?

Cheers,
Vlad

**Comment by mblondel** [comment]
+1 on my side

This is a high-quality implementation, with good documentation and tests. The check_estimator failure is a lack of flexibility on the scikit-learn side IMO. In the future, polylearn could implement more methods for learning polynomials, such as random features, for instance.

**Comment by jnothman** [comment]
> Should we make the scikit-learn tests more leninent with this scenario?

Yes. More Leninent tests:

![Leninent](http://cdn.quotesgram.com/small/8/91/174603499-Vladimir-Lenin-150x150.jpg)

Lenient too. I'll make an issue.

**Comment by fabianp** [comment]
![image](https://cloud.githubusercontent.com/assets/277639/16792870/d7830ade-48cc-11e6-8dd3-04d9ed18929b.png)

**Comment by fabianp** [comment]
ping @FedericoV

**Comment by vene** [comment]
@jnothman Trying to bring about the revolution, one subliminal typo at a time!

**Comment by fabianp** [comment]
+1 for me. I'm no expert in factorization machines but code/examples/doc look good to me.

**Comment by vene** [comment]
I added another example:
http://vene.ro/polylearn/auto_examples/plot_xor.html

Does the "two +1" rule hold here as well? Should I proceed to move the project or wait for further review?

**Comment by mblondel** [comment]
@ogrisel @arthurmensch You might be interested in this.

**Comment by vene** [comment]
Indeed! BTW I loved your ICML paper, @arthurmensch !

On July 13, 2016 7:19:23 PM EDT, Mathieu Blondel <notifications@github.com> wrote:
>@ogrisel @arthurmensch You might be interested in this.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/scikit-learn-contrib/scikit-learn-contrib/issues/7#issuecomment-232514682

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by arthurmensch** [comment]
Great! I reckon it implements some ideas presented in your ICML paper? And
beyond already?
Le 14 juil. 2016 01:19, "Mathieu Blondel" <notifications@github.com> a
écrit :

**Comment by mblondel** [comment]
It implements the two CD solvers described in my paper.

**Comment by amueller** [comment]
leninent = lenin + ent?

**Comment by vene** [comment]
I went ahead and moved the repository. Thanks everyone!
