### ISSUE TITLE
Request for inclusion for hdbscan clustering library

### ISSUE THREAD

**Issue by lmcinnes** [scikit-learn-contrib/scikit-learn-contrib#8]
Request for project inclusion in scikit-learn-contrib

* Project name: hdbscan
* Project description: A clustering library implementing the HDBSCAN* and Robust Single Linkage density based clustering algorithms.
* Authors: Leland McInnes, John Healy, Steve Astels
* Current repository: https://github.com/lmcinnes/hdbscan
* Requirements:
 * [X] scikit-learn compatible (check_estimator passed [part of the unit test suite]
 * [X] Documentation (guide, API reference, example gallery) [see https://hdbscan.readthedocs.io]
 * [X] Unit tests (coverage: 93%) [This could be higher, but there are some issues supporting older numpy versions that force it down a little]
 * [X] Python3 compatible [As per unit test builds against python 3 on Travis CI]
 * [X] PEP8 compliant [As far as I know; there may be a few lingering line length issues, but I can fix those if required]
 * [X] Continuous integration [Travis CI set up recently]

**Comment by amueller** [comment]
Awesome, thanks!

**Comment by mblondel** [comment]
Great project! 

Could you give me the account names that should be admin? Thanks!

**Comment by lmcinnes** [comment]
Sure, 

@lmcinnes, @jc-healy and @c-north

Thanks.

**Comment by mblondel** [comment]
@lmcinnes I added you as a scikit-learn-contrib owner. This should give you permissions to transfer your repository. I also created a hdbscan team and added the members you gave.

Once this is done, could you:
* add your project there: https://github.com/scikit-learn-contrib/scikit-learn-contrib
* fork the transferred repository to your account (this way, links to https://github.com/lmcinnes/hdbscan will still work)
* add the repository to the hdbscan team

Thanks!

**Comment by GaelVaroquaux** [comment]
Welcome! This is a nice project!

**Comment by mblondel** [comment]
Thank you for the transfer! Closing.
